services:
    custom-next:
        build: https://git.jannickus.com/jbath/docker-next.git

        networks:
            - traefik_net

        volumes:
            - $VOLUME:/project-data

        ports:
            - 3000

        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.${DRONE_REPO_NAME}.entrypoints=web'
            - 'traefik.http.routers.${DRONE_REPO_NAME}.rule=Host(`${DRONE_REPO_NAME}.prod.jannickus.com`)'

            - 'traefik.http.routers.${DRONE_REPO_NAME}https.entrypoints=websecure'
            - 'traefik.http.routers.${DRONE_REPO_NAME}https.rule=Host(`${DRONE_REPO_NAME}.prod.jannickus.com`)'
            - "traefik.http.routers.${DRONE_REPO_NAME}https.tls.certresolver=myresolver"
            - "traefik.http.services.${DRONE_REPO_NAME}https.loadbalancer.server.port=3000"
            - "traefik.http.routers.${DRONE_REPO_NAME}https.middlewares=global-websocket"

        container_name: $DRONE_REPO_NAME
        restart: always

networks:
    traefik_net:
        external: true
